"""Regenerate the edit lists from a pre-photos and a photos version of the app.

    # template with voice mode (the current fullstack-ai-assistant template)
    python scripts/maintain/make_patches.py <pre-photos> <photos> scripts/patches.py
    # template without voice mode
    python scripts/maintain/make_patches.py <pre-photos-no-voice> <photos-no-voice> scripts/patches_no_voice.py

For each wired file (FILES), diffs the two versions and emits the smallest
(old -> new) edits whose context makes them unique, then checks that applying
them in order reproduces the photos version exactly.
"""

import difflib
import sys
from pathlib import Path

BEFORE = Path(sys.argv[1])
AFTER = Path(sys.argv[2])
OUT = Path(sys.argv[3])
VARIANT = "without voice mode" if "no_voice" in OUT.name else "with voice mode"

FILES = [
    "api/app/core/config.py",
    "api/app/main.py",
    "api/app/schemas.py",
    "api/app/providers/ollama.py",
    "api/app/providers/anthropic.py",
    "api/app/providers/openai_compat.py",
    "api/app/providers/registry.py",
    "api/app/services/chat.py",
    "api/app/routes/chat.py",
    "api/app/routes/models.py",
    "api/tests/conftest.py",
    "api/tests/test_models.py",
    "api/.env.example",
    "web/lib/types.ts",
    "web/lib/api.ts",
    "web/hooks/use-chat.ts",
    "web/components/chat/composer.tsx",
    "web/components/chat/message.tsx",
    "web/components/chat/message-list.tsx",
    "web/components/chat/model-picker.tsx",
    "web/components/chat/app-sidebar.tsx",
    "web/components/chat/chat-app.tsx",
    # Docs: optional (a customised README is reported, not an error).
    "README.md",
    "api/README.md",
    "web/README.md",
]


def edits_for(before: str, after: str) -> list[tuple[str, str]]:
    """Smallest shared context n for which every hunk is a safe anchored edit.

    Nearby changes are merged into one hunk (difflib's grouped opcodes), so
    hunks never overlap.
    """
    a = before.splitlines(keepends=True)
    b = after.splitlines(keepends=True)
    sm = difflib.SequenceMatcher(a=a, b=b, autojunk=False)
    for n in range(1, 20):
        out = []
        for group in sm.get_grouped_opcodes(n):
            i1, i2 = group[0][1], group[-1][2]
            j1, j2 = group[0][3], group[-1][4]
            out.append(("".join(a[i1:i2]), "".join(b[j1:j2])))
        safe = all(
            old.strip()
            and before.count(old) == 1
            and after.count(new) == 1
            and before.count(new) == 0  # so "NEW present" reliably means "already applied"
            for old, new in out
        )
        if not safe:
            continue
        text = before
        for old, new in out:
            if text.count(old) != 1:
                break
            text = text.replace(old, new)
        else:
            if text == after:
                return out
    raise SystemExit("could not build safe edits")


lines = [
    f'"""Anchored edits that wire "Add photos" into the fullstack-ai-assistant template ({VARIANT}).',
    "",
    "Generated by scripts/maintain/make_patches.py from the verified pre-photos and",
    "photos versions of each file. Each edit replaces OLD (which must appear exactly",
    "once) with NEW. An edit whose NEW text is already present counts as applied, so",
    "the installer is idempotent.",
    '"""',
    "",
    "EDITS: list[tuple[str, str, str]] = [",
]
total = 0
for f in FILES:
    if not (BEFORE / f).exists() or not (AFTER / f).exists():
        continue
    before = (BEFORE / f).read_text()
    after = (AFTER / f).read_text()
    if before == after:
        continue
    for old, new in edits_for(before, after):
        lines.append(f"    ({f!r}, {old!r}, {new!r}),")
        total += 1
lines.append("]")
OUT.write_text("\n".join(lines) + "\n")
print(f"{total} edits in {len(FILES)} files -> {OUT}")
